
package travelagency;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.apache.log4j.Logger;
import org.hibernate.HibernateException;
import org.hibernate.Transaction;
import org.hibernate.exception.JDBCConnectionException;


/**
 * This class represents one of GUI windows.
 *
 * @author Konrad
 * @version 1.0
 */
public class Login extends javax.swing.JFrame {

    ImageIcon icon = new ImageIcon("icon.png");
    ImageIcon logo = new ImageIcon("logo.png");
    ProgressBar b = new ProgressBar();
    private loginProgress p1;
    private static final Logger logger = Logger.getLogger(Login.class.getName()); 
    

    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    

    private void login(){
       
        if(!nickTextField.getText().isEmpty())
        {
            Transaction tx = null;
            
            try{
                org.hibernate.Session session = HibernateUtil.getSessionFactory().openSession();
                tx = session.beginTransaction();
                String login = nickTextField.getText();
                String pass = String.valueOf(passPasswordField.getPassword());
                List personss =  session.createQuery("FROM Person WHERE login = ? and password = ?").setString(0, login)
                        .setString(1, pass).list();
                Person sample = new Person();
                
                if(personss.size()>0)
                {
                    sample = (Person)personss.get(0);
                    errorLabel.setText("");
                    logger.info("LOGGED IN AS: " + sample.getLogin() + " (NAME: " + sample.getFirstName() + " SURNAME: " + sample.getLastName() + ")");
                    b.setVisible(false);
                    this.setVisible(false);
                    new Main(sample).setVisible(true);
                }else
                {
                    errorLabel.setForeground(Color.red);
                    errorLabel.setText("Błędny login lub hasło!");
                    logger.warn("WRONG LOGIN OR PASSWORD");
                }
                tx.commit();              
                b.setVisible(false);
            }catch (JDBCConnectionException ex) {
                logger.warn(ex);
                if (tx!=null) tx.rollback();
                b.setVisible(false);
                JOptionPane.showMessageDialog(null,"Brak połączenia z bazą danych!\nNie zalogowano!" ,"Błąd logowania!",JOptionPane.ERROR_MESSAGE);
            }catch(HibernateException e){
                b.setVisible(false);
                e.printStackTrace();
                logger.warn(e);
                errorLabel.setForeground(Color.red);
            }   
        }else
        {
            b.setVisible(false);
            errorLabel.setForeground(Color.red);
            errorLabel.setText("Podaj login i hasło!");
        }
    }
    class loginProgress extends SwingWorker <Void, Void>{
        @Override
        protected Void doInBackground(){
        b.setVisible(true);
        b.setProgressLabel("Logowanie...");
        login();
        return null;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nickLabel = new javax.swing.JLabel();
        nickTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passPasswordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Logowanie");
        setIconImage(icon.getImage());

        nickLabel.setText("Login:");

        nickTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enterHandler(evt);
            }
        });

        passwordLabel.setText("Password:");

        passPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enterHandler(evt);
            }
        });

        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/log_in.png"))); // NOI18N
        loginButton.setText("Zaloguj");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enterHandler(evt);
            }
        });

        registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_male_2_add.png"))); // NOI18N
        registerButton.setText("Rejestruj");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        registerButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enterRegisterHandler(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordLabel)
                    .addComponent(nickLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(errorLabel)
                    .addComponent(registerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(nickTextField)
                    .addComponent(passPasswordField))
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nickLabel)
                    .addComponent(nickTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
            
        if(!nickTextField.getText().isEmpty())
        {
            p1 = new loginProgress();
            p1.execute();          
        }else
        {
            b.setVisible(false);
            errorLabel.setForeground(Color.red);
            errorLabel.setText("Podaj login i hasło!");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        new Register().setVisible(true);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void enterHandler(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enterHandler
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) 
        {
            if(!nickTextField.getText().isEmpty())
            {
                p1 = new loginProgress();
                p1.execute();          
            }else
            {
                b.setVisible(false);
                errorLabel.setForeground(Color.red);
                errorLabel.setText("Podaj login i hasło!");
            }
        };
    }//GEN-LAST:event_enterHandler

    private void enterRegisterHandler(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enterRegisterHandler
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) new Register().setVisible(true);
    }//GEN-LAST:event_enterRegisterHandler

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            logger.warn(ex);
        } catch (InstantiationException ex) {
            logger.warn(ex);
        } catch (IllegalAccessException ex) {
            logger.warn(ex);
        } catch (UnsupportedLookAndFeelException ex) {
            logger.warn(ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel nickLabel;
    private javax.swing.JTextField nickTextField;
    private javax.swing.JPasswordField passPasswordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton registerButton;
    // End of variables declaration//GEN-END:variables
}
